AddCSLuaFile("mta/gamemode/client/cl_hud.lua")
AddCSLuaFile("mta/gamemode/client/mta_hud/hud.lua")
AddCSLuaFile("mta/gamemode/client/mta_hud/map.lua")
AddCSLuaFile("mta/gamemode/client/mta_hud/daily_challenges.lua")
AddCSLuaFile("mta/gamemode/client/mta_hud/vault.lua")
AddCSLuaFile("mta/gamemode/client/mta_hud/statuses.lua")

resource.AddFile("materials/vgui/mta_hud/maps/rp_unioncity.vmt")
resource.AddFile("materials/vgui/mta_hud/hpicon.vmt")
resource.AddFile("materials/vgui/mta_hud/apicon.vmt")
resource.AddFile("materials/vgui/mta_hud/secammo.vmt")
resource.AddFile("materials/vgui/mta_hud/ammobg.vmt")
resource.AddFile("resource/fonts/altehaasgroteskbold.ttf")
resource.AddFile("resource/fonts/orbitron black.ttf")